name: Java CI with Gradle

# 동작 조건 설정 : main 브랜치에 push가 발생할 경우 동작한다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 1. Java 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3-1. Gradle 권한 부여
      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      # 3-2. Spring Boot 애플리케이션 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4. Docker 이미지 빌드
      - name: docker image build
        run: docker build -t jokubattle2/jokubattle .

      # 5. DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: jokubattle2
          password: joku12345

      # 6. Docker Hub 이미지 푸시
      - name: docker Hub push
        run: docker push jokubattle2/jokubattle

  deploy:
    # build-docker-image (위)과정이 완료되어야 실행됩니다.
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      # GCP 로그인
      - name: GCP login and docker image pull and run
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER_NAME}}
          port: 22
          key: ${{secrets.GCP_KEY}}

          script: |
            echo "도커 로그인"
            sudo docker login -u jokubattle2 -p joku12345
            
            echo "사용하지 않는 컨테이너 제거"
            sudo docker stop jokubattle
            sudo docker rm jokubattle
            
            echo "도커 허브에서 이미지 가져오기"
            sudo docker pull jokubattle2/jokubattle
            
            echo "가져온 이미지를 컨테이너로 띄우기"
            sudo docker run --network jokubattle --name jokubattle -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/jokubattle
            sudo docker image prune -f
